### ISSUE TITLE
キャラクターの制御

### ISSUE THREAD

**Issue by Fuhma** [matsumoto36/Drop#2]
・ジャイロによるキャラクターの操作
・大きさによって操作難度の変化(慣性の変化＆加速度の変化)
・アイテム取得による挙動の変化
・ダメージによるHPの減少
・雫取得によるHPの回復
・内部のHP(数値)の実装　何秒間かで雫１個分減少
・現在のHPによって状態を変化させる
(内部数値によって大きさを変化・瀕死時には専用状態に変更)

**Comment by Fuhma** [comment]
・各々の挙動に対してのSEの実装
・オプションボタンの内部の音量調整(SE・BGMの二種類)
ゲージは10段階ほどに分けて指で調整できるように
・各シーンにおいてのBGMの実装

**Comment by matsumoto36** [comment]
終わりました(はあと)

**Comment by Fuhma** [comment]
おとぅかれさまでぇす
